### ISSUE TITLE
Problem with manuals in xgap-4.25 

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/xgap#3] opened 2016-11-06 09:33 UTC
The new release has been picked up, but breaks `helpsys.tst`:
```
########> Diff in /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GA\
PCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/tst/teststanda\
rd/helpsys.tst, line 24:
# Input is:
for i in [1..Length(HELP_LAST.TOPICS)] do HELP(String(i)); od;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionStream' on 1 arguments
########
```
That's not very illuminating error message, but repeating commands from the test in a GAP session I was able to investigate the break loop and figured out that this is a problem in XGAP. You don't have to load XGAP for that, since the manuals are available in an ordinary GAP session. First, call
```
gap> ??xgap
Help: several entries match this topic - type ?2 to get match [2]

[1] ITC (not loaded): Starting XGAP
[2] XGAP (not loaded): What you can do with XGAP
[3] XGAP (not loaded): What you need to install XGAP
[4] XGAP (not loaded): Colors in XGAP
[5] XGAP (not loaded): What is XGAP?
[6] XGAP (not loaded): Installing XGAP
[7] XGAP (not loaded): Differences to XGAP 3
```

Now, if you enter any number except 4, the help text is displayed. Otherwise, there is an error:
```
gap> ?4
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionStream' on 1 arguments called from
PositionStream( stream 
 ) at /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GAPCOPTS/64bui\
ld/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/lib/helpdef.gi:306 called \
from
HELP_CHAPTER_INFO( book, chapter 
 ) at /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GAPCOPTS/64bui\
ld/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/lib/helpt2t.gi:220 called \
from
HELP_PRINT_SECTION_TEXT( info, chnr, secnr 
 ) at /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GAPCOPTS/64bui\
ld/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/lib/helpdef.gi:669 called \
from
HELP_BOOK_HANDLER.(book.handler).HelpData( book, entrynr, type 
 ) at /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GAPCOPTS/64bui\
ld/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/lib/helpbase.gi:782 called\
 from
HELP_PRINT_MATCH( HELP_LAST.TOPICS[nr] 
 ); at /mnt/disk2/hudson-slave/workspace/GAP-update-release-test/GAPCOPTS/64bu\
ild/GAPGMP/gmp/GAPTARGET/standard/label/64bit/gap4r8/lib/helpbase.gi:1017 call\
ed from
...  at line 13 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by olexandr-konovalov** [comment] 2016-11-06 09:36
P.S. @fingolfin I am going to rewrap packages to use xgap-4.24 - if you will have a chance to stop me from doing that by fixing the problem and releasing xgap-4.26 today, please let me know to pick it up instead.

**Comment by fingolfin** [comment] 2016-11-06 10:39
Ugh, that's a very unhelpful error message in the GAP help system. I think that needs to be improved -- right now, I have no idea what's wrong.

**Comment by fingolfin** [comment] 2016-11-06 11:14
I cannot reproduces this on two different systems (my personal dev system, with OSX; and with a Debian box). For both, I am using GAP's master branch (though that shouldn't matter... should it...?). And I made sure that GAP only sees xgap-4.25 (freshly downloaded from github), no other version of xgap. And I started gap with `-A` to ensure Browse does not interfer (I don't think it does, but since your examples didn't use it, I wanted to make sure...

**Comment by olexandr-konovalov** [comment] 2016-11-06 11:31
The break look happens in HELP_CHAPTER_INFO. In the break loop, I inspect the `filename` variable, and it points to `pkg/xgap-4.25/doc/gobject.tex` file which is missing in the package (there is only `gobject.msk` there). The `gobject.tex` is present in XGAP 4.24 however.

**Comment by fingolfin** [comment] 2016-11-06 12:05
OK, fixed in 4.26.

**Closed as completed by fingolfin** 2016-11-06 12:05 UTC

**Comment by olexandr-konovalov** [comment] 2016-11-06 13:33
@fingolfin thanks, but https://gap-packages.github.io/xgap/ still serves 4.25

**Comment by fingolfin** [comment] 2016-11-06 13:35
Grrr, my fault -- I forgot to push gh-pages (this is intentionally a separate step, to allow testing the release before publishing it). Fixed now

**Comment by olexandr-konovalov** [comment] 2016-11-06 14:01
@fingolfin picked up 4.26 now, thanks
